### PR TITLE
Feature/implement script to generate amplify folder

### PR DESCRIPTION
**Pull request by kishorepran**
added a script to generate the model folder in amplify folder
the script was called from the update amplify script

Update .gitignore this change in introduced after running the update amplify script
I had other changes as well but did not commit as it might break for people with lower aws amplify versions
will revert this if needed. assuming this dosen't hurt

my aws amplify version 12.2.0, installed by home brew

### CODE REVIEW

**Comment by kishorepran** [comment]
CI is not succeeding due to a bug. Working on the fix

**Comment by kishorepran** [comment]
Update: the issue is exactly as mentioned here: https://github.com/aws-amplify/amplify-cli/issues/9941

However the work around does not help for CI i.e.
1. put no when it asks do you want to modify the backend.
2. running `amplify codegen models` post failure works locally, doesn't work in CI because the runner in CI exited already due to a previous failure.
3. creating a folder manually "amplify/generated/models" and re-running the script again works locally but fails in CI because the runner will exit with the first sign of failure.

Overall my pr does not fix the issue. I will still keep it open If any one has more experience with aws and would like to pair up with me to fix this.
 
Highlighted issue observations.

Screenshot 2023-07-31 at 5 38 59 PM

**Review by rinold — APPROVED** [review]

**Comment by kishorepran** [comment]
Hello All,

Please review this pr and help merge post updates. do let me know for any questions.

Update:
the fix for AWS update script is to run the 'amplify codegen models' after the build failure has happened.
this was done by breaking the step into parts:
1. run amplify setup
2. recover from error only if the above step failed.

Other Changes / Fixes:
1. Building project for tests was failing due to a compile time error. Fixed.
2. Running unit test failing (only when run test via command line) due to UI method being called from a background thread.
3. to focus on the current scope of work and no real unit test running (empty unit test files found for testing). test step is disabled until the project can run the unit test locally via command line using the command "xcodebuild test -scheme animeal -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=16.4""

Further changes proposed.
1. Drop steps that take significant time vs adding value. E.g. Set Default Scheme. It take 8 min where we can set a hardcoded scheme knowing that we are not using multiple schemes here.
2. Update to xcode 14.2
3. Put a check in build phases where the swiftLint step does not run again when we are on a CI.
4. Write a one unit test or point to any existing unit test and make them run happily in CI. Start with a single command to build and run unit test both in go.
5. remove un used libraries for unit test. i.e. Quick and Nimble. Or remove any other un used library.
CC: @rinold

**Comment by kishorepran** [comment]
Discussed updates with @rinold offline. Please tag me here for any issues post merge. Thanks :-)

**Pull request merged**
